workflows:
  ios-capacitor-workflow:
    name: OCL iOS Build

    instance_type: mac_mini_m1

    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v

      - name: Install dependencies
        script: |
          npm install

      - name: Build Vite app
        script: |
          npm run build

      - name: Verify dist exists
        script: |
          ls
          ls dist

      - name: Capacitor doctor
        script: |
          npx cap doctor

      - name: Remove old ios
        script: |
          rm -rf ios

      - name: Add iOS platform
        script: |
          npx cap add ios

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Verify iOS structure
        script: |
          ls ios
          ls ios/App

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build unsigned app
        script: |
          cd ios/App

          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Package IPA
        script: |
          mkdir Payload

          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -1)

          echo $APP_PATH

          cp -R "$APP_PATH" Payload/

          zip -r OCL.ipa Payload

    artifacts:
      - OCL.ipa